"""Pydantic models for structured data in the GroundTruth system."""

from typing import Any, Dict, List
from pydantic import BaseModel, Field


class ResearchPlan(BaseModel):
    """Structured research plan generated by the Strategist agent."""
    
    target_sector: str = Field(..., description="The real estate sector to analyze")
    geography: str = Field(..., description="Geographic region or market")
    currency: str = Field(default="USD", description="Currency for financial metrics")
    area_unit: str = Field(default="sqft", description="Unit for area measurements")
    search_queries: List[str] = Field(..., description="List of search queries for market research")


class AnalystOutput(BaseModel):
    """Quantitative analysis output from the Analyst agent."""
    
    key_metrics: Dict[str, Any] = Field(..., description="Key quantitative metrics extracted")
    charts_generated: List[str] = Field(default_factory=list, description="Paths to generated chart images")


class ReportDraft(BaseModel):
    """Complete report draft generated by the Writer agent."""
    
    executive_summary: str = Field(..., description="Executive summary section")
    key_takeaways: str = Field(..., description="Key takeaways bullet points")
    investment_thesis: str = Field(..., description="Investment thesis section")
    go_no_go_scorecard: str = Field(..., description="Go/No-Go scorecard table")
    macro_market_context: str = Field(..., description="Macro and market context section")
    market_overview: str = Field(..., description="Market overview section")
    data_analysis: str = Field(..., description="Data analysis section")
    risk_assessment: str = Field(..., description="Risk assessment section")
    conclusion: str = Field(..., description="Conclusion section")


class ReviewCritique(BaseModel):
    """Review feedback from the Auditor agent."""
    
    approved: bool = Field(..., description="Whether the report is approved")
    feedback: str = Field(..., description="Detailed feedback on the report")
    missing_data: List[str] = Field(default_factory=list, description="List of missing data or information")

