"""Pydantic models for structured data in the GroundTruth system."""

from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class ResearchPlan(BaseModel):
    """Structured research plan generated by the Strategist agent."""
    
    target_sector: str = Field(..., description="The real estate sector to analyze")
    geography: str = Field(..., description="Geographic region or market")
    currency: str = Field(default="USD", description="Currency for financial metrics")
    area_unit: str = Field(default="sqft", description="Unit for area measurements")
    search_queries: List[str] = Field(..., description="List of search queries for market research")


class AnalystOutput(BaseModel):
    """Quantitative analysis output from the Analyst agent."""
    
    key_metrics: Dict[str, Any] = Field(default_factory=dict, description="Key quantitative metrics extracted")
    chart_data: List[Dict[str, Any]] = Field(default_factory=list, description="List of chart specifications")
    charts_generated: List[str] = Field(default_factory=list, description="Paths to generated chart images")


class ReportDraft(BaseModel):
    """Complete report draft generated by the Writer agent."""
    
    executive_summary: Optional[str] = Field(None, description="Executive summary section")
    key_takeaways: Optional[str] = Field(None, description="Key takeaways bullet points")
    market_assessment: Optional[str] = Field(None, description="Neutral market assessment with summary table")
    case_studies: Optional[str] = Field(None, description="Table of recent transactions and case studies")
    macro_market_context: Optional[str] = Field(None, description="Macro and market context section")
    market_overview: Optional[str] = Field(None, description="Market overview section")
    data_analysis: Optional[str] = Field(None, description="Data analysis section")
    risk_assessment: Optional[str] = Field(None, description="Risk assessment section")
    conclusion: Optional[str] = Field(None, description="Conclusion section")
    competitive_landscape: Optional[str] = Field(None, description="Competitive landscape analysis")
    regulatory_policy_environment: Optional[str] = Field(None, description="Regulatory and policy environment section")
    pricing_valuation_analysis: Optional[str] = Field(None, description="Pricing and valuation analysis section")
    operational_considerations: Optional[str] = Field(None, description="Operational considerations section")


class ReviewCritique(BaseModel):
    """Review feedback from the Auditor agent."""
    
    approved: bool = Field(..., description="Whether the report is approved")
    feedback: str = Field(..., description="Detailed feedback on the report")
    missing_data: List[str] = Field(default_factory=list, description="List of missing data or information")

